# Generated by Django 4.2.7 on 2023-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_remove_orders_order_quantity_orders_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
