# Generated by Django 4.2.7 on 2023-12-22 07:46

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_logo_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to=products.models.image_upload),
        ),
    ]
