# Generated by Django 4.2.7 on 2023-12-22 07:51

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_upload_path),
        ),
    ]
